### ISSUE TITLE
`FileReader` class is giving error

### ISSUE THREAD

**Issue by debpal** [swat-model/pySWATPlus#43]
@zepholus, please solve this issue with high priority.

**Describe the bug**
I am trying to read the DataFrame from a simulation generated file `channel_sdmorph_yr.txt`. I am getting error. However, the file `channel_sd_yr.txt` is not giving any error.

**Code Snippet** (if applicable):
```python
file_reader = pySWATPlus.FileReader(
    path='channel_sdmorph_yr.txt',
    has_units=has_units
)

# DataFrame
df = file_reader.df
```

## Data link

[channel_sdmorph_yr.txt](https://github.com/user-attachments/files/21890579/channel_sdmorph_yr.txt)
 

**Expected behavior**
A DataFrame

## Actual Behavior
Error due to unit row checking in simulation generated output file.

**Error Output** (if applicable):
```plaintext
ValueError: Units row could not be parsed correctly. Check if your file is well-formed.
```

## Additional Context
if it is a simulation generated file, then simply return the `DataFrame` without unit checking because we are not overwriting the file.

Mu suggestion is to initiate the `FileReader` class by 

```python
def __init__(
    self,
    path: str | pathlib.Path,
    has_units: bool
):

    if not isinstance(path, (str, pathlib.Path)):
        raise TypeError('path must be a string or Path object')

    path = pathlib.Path(path).resolve()

    if not path.is_file():
        raise FileNotFoundError('file does not exist')

    self.has_units = has_units

    # if output ends with _day, _mon, _yr, _aa, _subday (removing the suffix), it means is an output file from SWAT.
    # if file is a csv is output file
    self.is_output_file = path.stem.endswith(('_day', '_mon', '_yr', '_aa', '_subday')) or path.suffix == '.csv'

    # skips the header
    skip_rows = [0, 2] if self.has_units else [0]

    self.df = utils._load_file(path, skip_rows=skip_rows)

    self.path = path
```

Then rest of the code should move to `overwrite_file` method because the `DataFrame` is generated correctly up to here.

## Checklist
- [x ] I have searched for existing issues to avoid duplicates.
- [x ] I have tested with the latest version of the library.
- [x ] I have provided a minimal, reproducible example.
- [x ] I am willing to assist with further debugging if needed.

**Comment by zepholus** [comment]
Fixed in [Commit #150c788](https://github.com/swat-model/pySWATPlus/commit/150c788df30c54e7447a5734b7f63544778bc303).

**Comment by debpal** [comment]
@zepholus Thanks for fixing the issue! I still have a question.

In our workflow we have two types of files:

- Pre-simulation files (inputs, configurations)
- Simulation-generated files (outputs)

We already added a condition to detect simulation-generated files so that they cannot be overwritten.

Given that, what is the purpose of the code after this line for a simulation-generated file?

````python
self.df = utils._load_file(path, skip_rows=skip_rows)
```
